/*
 * Trident - A Multithreaded Server Alternative
 * Copyright 2017 The TridentSDK Team
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package net.tridentsdk.base;

import java.util.HashMap;
import java.util.Map;
import javax.annotation.concurrent.Immutable;
import net.tridentsdk.util.Int2ReferenceOpenHashMap;

/**
 * Represents the type of a block or an item.
 *
 * GENERATED BY /scripts/ids/generate.py<br>
 *
 * Content sourced from the Official Minecraft Wiki, http://minecraft.gamepedia.com/<br>
 * Minecraft Wiki content, which consists of all content on the pages used, is licensed under
 * <a href="https://creativecommons.org/licenses/by-nc-sa/3.0/">Attribution-NonCommercial-ShareAlike 3.0 Unported (CC BY-NC-SA 3.0)</a>.<br>
 *
 * Minecraft is a registered trademark of Mojang AB.
 *
 * @author TridentSDK
 * @since 0.3-alpha-DP
 */
@Immutable
public enum Substance {

    // BEGIN BLOCKS

    AIR(0, "minecraft:air", "Air", false, false, false, false, false),
    STONE(1, "minecraft:stone", "Stone", true, true, false, false, false),
    GRASS_BLOCK(2, "minecraft:grass", "Grass Block", false, false, false, false, false),
    DIRT(3, "minecraft:dirt", "Dirt", true, true, false, false, false),
    COBBLESTONE(4, "minecraft:cobblestone", "Cobblestone", false, false, false, false, false),
    WOOD_PLANKS(5, "minecraft:planks", "Wood Planks", true, true, false, false, false),
    SAPLING(6, "minecraft:sapling", "Sapling", true, true, false, false, false),
    BEDROCK(7, "minecraft:bedrock", "Bedrock", false, false, false, false, false),
    FLOWING_WATER(8, "minecraft:flowing_water", "Water", true, false, false, false, false),
    WATER(9, "minecraft:water", "Water", true, false, false, false, false),
    FLOWING_LAVA(10, "minecraft:flowing_lava", "Lava", true, false, false, false, false),
    LAVA(11, "minecraft:lava", "Lava", true, false, false, false, false),
    SAND(12, "minecraft:sand", "Sand", true, true, false, false, false),
    GRAVEL(13, "minecraft:gravel", "Gravel", false, false, false, false, false),
    GOLD_ORE(14, "minecraft:gold_ore", "Gold Ore", false, false, false, false, false),
    IRON_ORE(15, "minecraft:iron_ore", "Iron Ore", false, false, false, false, false),
    COAL_ORE(16, "minecraft:coal_ore", "Coal Ore", false, false, false, false, false),
    WOOD(17, "minecraft:log", "Wood", true, true, false, false, false),
    LEAVES(18, "minecraft:leaves", "Leaves", true, true, false, false, false),
    SPONGE(19, "minecraft:sponge", "Sponge", true, true, false, false, false),
    GLASS(20, "minecraft:glass", "Glass", false, false, false, false, false),
    LAPIS_LAZULI_ORE(21, "minecraft:lapis_ore", "Lapis Lazuli Ore", false, false, false, false, false),
    LAPIS_LAZULI_BLOCK(22, "minecraft:lapis_block", "Lapis Lazuli Block", false, false, false, false, false),
    DISPENSER(23, "minecraft:dispenser", "Dispenser", true, false, true, false, false),
    SANDSTONE(24, "minecraft:sandstone", "Sandstone", true, true, false, false, false),
    NOTE_BLOCK(25, "minecraft:noteblock", "Note Block", false, false, true, false, false),
    BED(26, "minecraft:bed", "Bed", true, false, false, true, false),
    POWERED_RAIL(27, "minecraft:golden_rail", "Powered Rail", true, false, false, false, false),
    DETECTOR_RAIL(28, "minecraft:detector_rail", "Detector Rail", true, false, false, false, false),
    STICKY_PISTON(29, "minecraft:sticky_piston", "Sticky Piston", true, false, false, false, false),
    COBWEB(30, "minecraft:web", "Cobweb", false, false, false, false, false),
    GRASS(31, "minecraft:tallgrass", "Grass", true, true, false, false, false),
    DEAD_BUSH(32, "minecraft:deadbush", "Dead Bush", false, false, false, false, false),
    PISTON(33, "minecraft:piston", "Piston", true, false, false, false, false),
    PISTON_HEAD(34, "minecraft:piston_head", "Piston Head", true, false, false, false, false),
    WOOL(35, "minecraft:wool", "Wool", true, true, false, false, false),
    BLOCK_MOVED_BY_PISTON(36, "minecraft:piston_extension", "Block moved by Piston", false, false, true, false, false),
    DANDELION(37, "minecraft:yellow_flower", "Dandelion", false, false, false, false, false),
    POPPY(38, "minecraft:red_flower", "Poppy", true, true, false, false, false),
    BROWN_MUSHROOM(39, "minecraft:brown_mushroom", "Brown Mushroom", false, false, false, false, false),
    RED_MUSHROOM(40, "minecraft:red_mushroom", "Red Mushroom", false, false, false, false, false),
    BLOCK_OF_GOLD(41, "minecraft:gold_block", "Block of Gold", false, false, false, false, false),
    BLOCK_OF_IRON(42, "minecraft:iron_block", "Block of Iron", false, false, false, false, false),
    DOUBLE_STONE_SLAB(43, "minecraft:double_stone_slab", "Double Stone Slab", true, true, false, false, false),
    STONE_SLAB(44, "minecraft:stone_slab", "Stone Slab", true, true, false, false, false),
    BRICKS(45, "minecraft:brick_block", "Bricks", false, false, false, false, false),
    TNT(46, "minecraft:tnt", "TNT", false, false, false, false, false),
    BOOKSHELF(47, "minecraft:bookshelf", "Bookshelf", false, false, false, false, false),
    MOSS_STONE(48, "minecraft:mossy_cobblestone", "Moss Stone", false, false, false, false, false),
    OBSIDIAN(49, "minecraft:obsidian", "Obsidian", false, false, false, false, false),
    TORCH(50, "minecraft:torch", "Torch", true, false, false, false, false),
    FIRE(51, "minecraft:fire", "Fire", true, false, false, false, false),
    MONSTER_SPAWNER(52, "minecraft:mob_spawner", "Monster Spawner", false, false, true, false, false),
    OAK_WOOD_STAIRS(53, "minecraft:oak_stairs", "Oak Wood Stairs", true, false, false, false, false),
    CHEST(54, "minecraft:chest", "Chest", true, false, true, false, false),
    REDSTONE_WIRE(55, "minecraft:redstone_wire", "Redstone Wire", true, false, false, true, false),
    DIAMOND_ORE(56, "minecraft:diamond_ore", "Diamond Ore", false, false, false, false, false),
    BLOCK_OF_DIAMOND(57, "minecraft:diamond_block", "Block of Diamond", false, false, false, false, false),
    CRAFTING_TABLE(58, "minecraft:crafting_table", "Crafting Table", false, false, false, false, false),
    WHEAT_CROP(59, "minecraft:wheat", "Wheat", true, false, false, true, false),
    FARMLAND(60, "minecraft:farmland", "Farmland", true, false, false, false, false),
    FURNACE(61, "minecraft:furnace", "Furnace", true, false, true, false, false),
    BURNING_FURNACE(62, "minecraft:lit_furnace", "Burning Furnace", true, false, true, false, false),
    SIGN(63, "minecraft:standing_sign", "Sign", true, false, true, true, false),
    OAK_DOOR(64, "minecraft:wooden_door", "Oak Door", true, false, false, true, false),
    LADDER(65, "minecraft:ladder", "Ladder", true, false, false, false, false),
    RAIL(66, "minecraft:rail", "Rail", true, false, false, false, false),
    COBBLESTONE_STAIRS(67, "minecraft:stone_stairs", "Cobblestone Stairs", true, false, false, false, false),
    WALL_SIGN(68, "minecraft:wall_sign", "Sign", true, false, true, true, false),
    LEVER(69, "minecraft:lever", "Lever", true, false, false, false, false),
    STONE_PRESSURE_PLATE(70, "minecraft:stone_pressure_plate", "Stone Pressure Plate", true, false, false, false, false),
    IRON_DOOR(71, "minecraft:iron_door", "Iron Door", true, false, false, true, false),
    WOODEN_PRESSURE_PLATE(72, "minecraft:wooden_pressure_plate", "Wooden Pressure Plate", true, false, false, false, false),
    REDSTONE_ORE(73, "minecraft:redstone_ore", "Redstone Ore", false, false, false, false, false),
    LIT_REDSTONE_ORE(74, "minecraft:lit_redstone_ore", "Redstone Ore", false, false, false, false, false),
    REDSTONE_TORCH(75, "minecraft:unlit_redstone_torch", "Redstone Torch", true, false, false, false, false),
    LIT_REDSTONE_TORCH(76, "minecraft:redstone_torch", "Redstone Torch", true, false, false, false, false),
    STONE_BUTTON(77, "minecraft:stone_button", "Stone Button", true, false, false, false, false),
    SNOW_LAYER(78, "minecraft:snow_layer", "Snow", true, true, false, false, false),
    ICE(79, "minecraft:ice", "Ice", false, false, false, false, false),
    SNOW(80, "minecraft:snow", "Snow", false, false, false, false, false),
    CACTUS(81, "minecraft:cactus", "Cactus", true, false, false, false, false),
    CLAY(82, "minecraft:clay", "Clay", false, false, false, false, false),
    SUGAR_CANE(83, "minecraft:reeds", "Sugar Cane", true, false, false, true, false),
    JUKEBOX(84, "minecraft:jukebox", "Jukebox", true, false, true, false, false),
    OAK_FENCE(85, "minecraft:fence", "Oak Fence", false, false, false, false, false),
    PUMPKIN(86, "minecraft:pumpkin", "Pumpkin", true, false, false, false, false),
    NETHERRACK(87, "minecraft:netherrack", "Netherrack", false, false, false, false, false),
    SOUL_SAND(88, "minecraft:soul_sand", "Soul Sand", false, false, false, false, false),
    GLOWSTONE(89, "minecraft:glowstone", "Glowstone", false, false, false, false, false),
    PORTAL(90, "minecraft:portal", "Portal", false, false, false, false, false),
    JACK_O_LANTERN(91, "minecraft:lit_pumpkin", "Jack o'Lantern", true, false, false, false, false),
    CAKE(92, "minecraft:cake", "Cake", true, false, false, true, false),
    REDSTONE_REPEATER(93, "minecraft:unpowered_repeater", "Redstone Repeater", true, false, false, true, false),
    LIT_REDSTONE_REPEATER(94, "minecraft:powered_repeater", "Redstone Repeater", true, false, false, true, false),
    STAINED_GLASS(95, "minecraft:stained_glass", "Stained Glass", true, true, false, false, false),
    TRAPDOOR(96, "minecraft:trapdoor", "Trapdoor", true, false, false, false, false),
    MONSTER_EGG(97, "minecraft:monster_egg", "Monster Egg", true, true, false, false, false),
    STONE_BRICKS(98, "minecraft:stonebrick", "Stone Bricks", true, true, false, false, false),
    BROWN_MUSHROOM_BLOCK(99, "minecraft:brown_mushroom_block", "Brown Mushroom", true, false, false, false, false),
    RED_MUSHROOM_BLOCK(100, "minecraft:red_mushroom_block", "Red Mushroom", true, false, false, false, false),
    IRON_BARS(101, "minecraft:iron_bars", "Iron Bars", false, false, false, false, false),
    GLASS_PANE(102, "minecraft:glass_pane", "Glass Pane", false, false, false, false, false),
    MELON(103, "minecraft:melon_block", "Melon", false, false, false, false, false),
    PUMPKIN_STEM(104, "minecraft:pumpkin_stem", "Pumpkin Stem", true, false, false, false, false),
    MELON_STEM(105, "minecraft:melon_stem", "Melon Stem", true, false, false, false, false),
    VINES(106, "minecraft:vine", "Vines", true, false, false, false, false),
    FENCE_GATE(107, "minecraft:fence_gate", "Fence Gate", true, false, false, false, false),
    BRICK_STAIRS(108, "minecraft:brick_stairs", "Brick Stairs", true, false, false, false, false),
    STONE_BRICK_STAIRS(109, "minecraft:stone_brick_stairs", "Stone Brick Stairs", true, false, false, false, false),
    MYCELIUM(110, "minecraft:mycelium", "Mycelium", false, false, false, false, false),
    LILY_PAD(111, "minecraft:waterlily", "Lily Pad", false, false, false, false, false),
    NETHER_BRICK(112, "minecraft:nether_brick", "Nether Brick", false, false, false, false, false),
    NETHER_BRICK_FENCE(113, "minecraft:nether_brick_fence", "Nether Brick Fence", false, false, false, false, false),
    NETHER_BRICK_STAIRS(114, "minecraft:nether_brick_stairs", "Nether Brick Stairs", true, false, false, false, false),
    NETHER_WART_CROP(115, "minecraft:nether_wart", "Nether Wart", true, false, false, true, false),
    ENCHANTMENT_TABLE(116, "minecraft:enchanting_table", "Enchantment Table", false, false, true, false, false),
    BREWING_STAND(117, "minecraft:brewing_stand", "Brewing Stand", true, false, true, true, false),
    CAULDRON(118, "minecraft:cauldron", "Cauldron", true, false, false, true, false),
    END_PORTAL(119, "minecraft:end_portal", "End Portal", false, false, true, false, false),
    END_PORTAL_FRAME(120, "minecraft:end_portal_frame", "End Portal Frame", true, false, false, false, false),
    END_STONE(121, "minecraft:end_stone", "End Stone", false, false, false, false, false),
    DRAGON_EGG(122, "minecraft:dragon_egg", "Dragon Egg", false, false, false, false, false),
    REDSTONE_LAMP(123, "minecraft:redstone_lamp", "Redstone Lamp", false, false, false, false, false),
    LIT_REDSTONE_LAMP(124, "minecraft:lit_redstone_lamp", "Redstone Lamp", false, false, false, false, false),
    DOUBLE_WOODEN_SLAB(125, "minecraft:double_wooden_slab", "Double Wooden Slab", true, true, false, false, false),
    WOODEN_SLAB(126, "minecraft:wooden_slab", "Wooden Slab", true, true, false, false, false),
    COCOA(127, "minecraft:cocoa", "Cocoa", true, false, false, true, false),
    SANDSTONE_STAIRS(128, "minecraft:sandstone_stairs", "Sandstone Stairs", true, false, false, false, false),
    EMERALD_ORE(129, "minecraft:emerald_ore", "Emerald Ore", false, false, false, false, false),
    ENDER_CHEST(130, "minecraft:ender_chest", "Ender Chest", true, false, true, false, false),
    TRIPWIRE_HOOK(131, "minecraft:tripwire_hook", "Tripwire Hook", true, false, false, false, false),
    TRIPWIRE(132, "minecraft:tripwire", "Tripwire", true, false, false, true, false),
    BLOCK_OF_EMERALD(133, "minecraft:emerald_block", "Block of Emerald", false, false, false, false, false),
    SPRUCE_WOOD_STAIRS(134, "minecraft:spruce_stairs", "Spruce Wood Stairs", true, false, false, false, false),
    BIRCH_WOOD_STAIRS(135, "minecraft:birch_stairs", "Birch Wood Stairs", true, false, false, false, false),
    JUNGLE_WOOD_STAIRS(136, "minecraft:jungle_stairs", "Jungle Wood Stairs", true, false, false, false, false),
    COMMAND_BLOCK(137, "minecraft:command_block", "Command Block", false, false, true, false, false),
    BEACON(138, "minecraft:beacon", "Beacon", false, false, true, false, false),
    COBBLESTONE_WALL(139, "minecraft:cobblestone_wall", "Cobblestone Wall", true, true, false, false, false),
    FLOWER_POT(140, "minecraft:flower_pot", "Flower Pot", true, false, true, true, false),
    CARROT_CROP(141, "minecraft:carrots", "Carrot", true, false, false, true, false),
    POTATO_CROP(142, "minecraft:potatoes", "Potato", true, false, false, true, false),
    WOODEN_BUTTON(143, "minecraft:wooden_button", "Wooden Button", true, false, false, false, false),
    MOB_HEAD(144, "minecraft:skull", "Mob head", true, false, true, true, false),
    ANVIL(145, "minecraft:anvil", "Anvil", true, true, false, false, false),
    TRAPPED_CHEST(146, "minecraft:trapped_chest", "Trapped Chest", true, false, true, false, false),
    LIGHT_WEIGHTED_PRESSURE_PLATE(147, "minecraft:light_weighted_pressure_plate", "Weighted Pressure Plate", true, false, false, false, false),
    HEAVY_WEIGHTED_PRESSURE_PLATE(148, "minecraft:heavy_weighted_pressure_plate", "Weighted Pressure Plate", true, false, false, false, false),
    REDSTONE_COMPARATOR(149, "minecraft:unpowered_comparator", "Redstone Comparator", true, false, false, true, false),
    LIT_REDSTONE_COMPARATOR(150, "minecraft:powered_comparator", "Redstone Comparator", true, false, false, false, false),
    DAYLIGHT_SENSOR(151, "minecraft:daylight_detector", "Daylight Sensor", false, false, true, false, false),
    BLOCK_OF_REDSTONE(152, "minecraft:redstone_block", "Block of Redstone", false, false, false, false, false),
    NETHER_QUARTZ_ORE(153, "minecraft:quartz_ore", "Nether Quartz Ore", false, false, false, false, false),
    HOPPER(154, "minecraft:hopper", "Hopper", true, false, true, false, false),
    BLOCK_OF_QUARTZ(155, "minecraft:quartz_block", "Block of Quartz", true, true, false, false, false),
    QUARTZ_STAIRS(156, "minecraft:quartz_stairs", "Quartz Stairs", true, false, false, false, false),
    ACTIVATOR_RAIL(157, "minecraft:activator_rail", "Activator Rail", true, false, false, false, false),
    DROPPER(158, "minecraft:dropper", "Dropper", true, false, true, false, false),
    STAINED_CLAY(159, "minecraft:stained_hardened_clay", "Stained Clay", true, true, false, false, false),
    STAINED_GLASS_PANE(160, "minecraft:stained_glass_pane", "Stained Glass Pane", true, true, false, false, false),
    LEAVES2(161, "minecraft:leaves2", "Leaves", true, true, false, false, false),
    WOOD2(162, "minecraft:log2", "Wood", true, true, false, false, false),
    ACACIA_WOOD_STAIRS(163, "minecraft:acacia_stairs", "Acacia Wood Stairs", true, false, false, false, false),
    DARK_OAK_WOOD_STAIRS(164, "minecraft:dark_oak_stairs", "Dark Oak Wood Stairs", true, false, false, false, false),
    SLIME_BLOCK(165, "minecraft:slime", "Slime Block", false, false, false, false, false),
    BARRIER(166, "minecraft:barrier", "Barrier", false, false, false, false, false),
    IRON_TRAPDOOR(167, "minecraft:iron_trapdoor", "Iron Trapdoor", true, false, false, false, false),
    PRISMARINE(168, "minecraft:prismarine", "Prismarine", true, true, false, false, false),
    SEA_LANTERN(169, "minecraft:sea_lantern", "Sea Lantern", false, false, false, false, false),
    HAY_BALE(170, "minecraft:hay_block", "Hay Bale", true, false, false, false, false),
    CARPET(171, "minecraft:carpet", "Carpet", true, true, false, false, false),
    HARDENED_CLAY(172, "minecraft:hardened_clay", "Hardened Clay", false, false, false, false, false),
    BLOCK_OF_COAL(173, "minecraft:coal_block", "Block of Coal", false, false, false, false, false),
    PACKED_ICE(174, "minecraft:packed_ice", "Packed Ice", false, false, false, false, false),
    LARGE_FLOWERS(175, "minecraft:double_plant", "Large Flowers", true, true, false, false, false),
    BANNER(176, "minecraft:standing_banner", "Banner", true, false, true, true, false),
    WALL_BANNER(177, "minecraft:wall_banner", "Banner", true, false, true, true, false),
    INVERTED_DAYLIGHT_SENSOR(178, "minecraft:daylight_detector_inverted", "Inverted Daylight Sensor", false, false, true, false, false),
    RED_SANDSTONE(179, "minecraft:red_sandstone", "Red Sandstone", true, true, false, false, false),
    RED_SANDSTONE_STAIRS(180, "minecraft:red_sandstone_stairs", "Red Sandstone Stairs", true, false, false, false, false),
    DOUBLE_RED_SANDSTONE_SLAB(181, "minecraft:double_stone_slab2", "Double Red Sandstone Slab", true, false, false, false, false),
    RED_SANDSTONE_SLAB(182, "minecraft:stone_slab2", "Red Sandstone Slab", true, false, false, false, false),
    SPRUCE_FENCE_GATE(183, "minecraft:spruce_fence_gate", "Spruce Fence Gate", false, false, false, false, false),
    BIRCH_FENCE_GATE(184, "minecraft:birch_fence_gate", "Birch Fence Gate", false, false, false, false, false),
    JUNGLE_FENCE_GATE(185, "minecraft:jungle_fence_gate", "Jungle Fence Gate", false, false, false, false, false),
    DARK_OAK_FENCE_GATE(186, "minecraft:dark_oak_fence_gate", "Dark Oak Fence Gate", false, false, false, false, false),
    ACACIA_FENCE_GATE(187, "minecraft:acacia_fence_gate", "Acacia Fence Gate", false, false, false, false, false),
    SPRUCE_FENCE(188, "minecraft:spruce_fence", "Spruce Fence", false, false, false, false, false),
    BIRCH_FENCE(189, "minecraft:birch_fence", "Birch Fence", false, false, false, false, false),
    JUNGLE_FENCE(190, "minecraft:jungle_fence", "Jungle Fence", false, false, false, false, false),
    DARK_OAK_FENCE(191, "minecraft:dark_oak_fence", "Dark Oak Fence", false, false, false, false, false),
    ACACIA_FENCE(192, "minecraft:acacia_fence", "Acacia Fence", false, false, false, false, false),
    SPRUCE_DOOR(193, "minecraft:spruce_door", "Spruce Door", true, false, false, true, false),
    BIRCH_DOOR(194, "minecraft:birch_door", "Birch Door", true, false, false, true, false),
    JUNGLE_DOOR(195, "minecraft:jungle_door", "Jungle Door", true, false, false, true, false),
    ACACIA_DOOR(196, "minecraft:acacia_door", "Acacia Door", true, false, false, true, false),
    DARK_OAK_DOOR(197, "minecraft:dark_oak_door", "Dark Oak Door", true, false, false, true, false),
    END_ROD(198, "minecraft:end_rod", "End Rod", false, false, false, false, false),
    CHORUS_PLANT(199, "minecraft:chorus_plant", "Chorus Plant", false, false, false, false, false),
    CHORUS_FLOWER(200, "minecraft:chorus_flower", "Chorus Flower", false, false, false, false, false),
    PURPUR_BLOCK(201, "minecraft:purpur_block", "Purpur Block", false, false, false, false, false),
    PURPUR_PILLAR(202, "minecraft:purpur_pillar", "Purpur Pillar", false, false, false, false, false),
    PURPUR_STAIRS(203, "minecraft:purpur_stairs", "Purpur Stairs", false, false, false, false, false),
    PURPUR_DOUBLE_SLAB(204, "minecraft:purpur_double_slab", "Purpur Double Slab", false, false, false, false, false),
    PURPUR_SLAB(205, "minecraft:purpur_slab", "Purpur Slab", false, false, false, false, false),
    END_STONE_BRICKS(206, "minecraft:end_bricks", "End Stone Bricks", false, false, false, false, false),
    BEETROOT_SEEDS_CROP(207, "minecraft:beetroots", "Beetroot Seeds", false, false, false, false, false),
    GRASS_PATH(208, "minecraft:grass_path", "Grass Path", false, false, false, false, false),
    END_GATEWAY(209, "minecraft:end_gateway", "End Gateway", false, false, false, false, false),
    REPEATING_COMMAND_BLOCK(210, "minecraft:repeating_command_block", "Repeating Command Block", false, false, true, false, false),
    CHAIN_COMMAND_BLOCK(211, "minecraft:chain_command_block", "Chain Command Block", false, false, true, false, false),
    FROSTED_ICE(212, "minecraft:frosted_ice", "Frosted Ice", true, false, false, false, false),
    MAGMA_BLOCK(213, "minecraft:magma", "Magma Block", false, false, false, false, false),
    NETHER_WART_BLOCK(214, "minecraft:nether_wart_block", "Nether Wart Block", false, false, false, false, false),
    RED_NETHER_BRICK(215, "minecraft:red_nether_brick", "Red Nether Brick", false, false, false, false, false),
    BONE_BLOCK(216, "minecraft:bone_block", "Bone Block", false, false, false, false, false),
    STRUCTURE_VOID(217, "minecraft:structure_void", "Structure Void", false, false, false, false, false),
    OBSERVER(218, "minecraft:observer", "Observer", false, false, false, false, false),
    WHITE_SHULKER_BOX(219, "minecraft:white_shulker_box", "White Shulker Box", false, false, false, false, false),
    ORANGE_SHULKER_BOX(220, "minecraft:orange_shulker_box", "Orange Shulker Box", false, false, false, false, false),
    MAGENTA_SHULKER_BOX(221, "minecraft:magenta_shulker_box", "Magenta Shulker Box", false, false, false, false, false),
    LIGHT_BLUE_SHULKER_BOX(222, "minecraft:light_blue_shulker_box", "Light Blue Shulker Box", false, false, false, false, false),
    YELLOW_SHULKER_BOX(223, "minecraft:yellow_shulker_box", "Yellow Shulker Box", false, false, false, false, false),
    LIME_SHULKER_BOX(224, "minecraft:lime_shulker_box", "Lime Shulker Box", false, false, false, false, false),
    PINK_SHULKER_BOX(225, "minecraft:pink_shulker_box", "Pink Shulker Box", false, false, false, false, false),
    GRAY_SHULKER_BOX(226, "minecraft:gray_shulker_box", "Gray Shulker Box", false, false, false, false, false),
    LIGHT_GRAY_SHULKER_BOX(227, "minecraft:light_gray_shulker_box", "Light Gray Shulker Box", false, false, false, false, false),
    CYAN_SHULKER_BOX(228, "minecraft:cyan_shulker_box", "Cyan Shulker Box", false, false, false, false, false),
    PURPLE_SHULKER_BOX(229, "minecraft:purple_shulker_box", "Purple Shulker Box", false, false, false, false, false),
    BLUE_SHULKER_BOX(230, "minecraft:blue_shulker_box", "Blue Shulker Box", false, false, false, false, false),
    BROWN_SHULKER_BOX(231, "minecraft:brown_shulker_box", "Brown Shulker Box", false, false, false, false, false),
    GREEN_SHULKER_BOX(232, "minecraft:green_shulker_box", "Green Shulker Box", false, false, false, false, false),
    RED_SHULKER_BOX(233, "minecraft:red_shulker_box", "Red Shulker Box", false, false, false, false, false),
    BLACK_SHULKER_BOX(234, "minecraft:black_shulker_box", "Black Shulker Box", false, false, false, false, false),
    WHITE_GLAZED_TERRACOTTA(235, "minecraft:white_glazed_terracotta", "White Glazed Terracotta", false, false, false, false, false),
    ORANGE_GLAZED_TERRACOTTA(236, "minecraft:orange_glazed_terracotta", "Orange Glazed Terracotta", false, false, false, false, false),
    MAGENTA_GLAZED_TERRACOTTA(237, "minecraft:magenta_glazed_terracotta", "Magenta Glazed Terracotta", false, false, false, false, false),
    LIGHT_BLUE_GLAZED_TERRACOTTA(238, "minecraft:light_blue_glazed_terracotta", "Light Blue Glazed Terracotta", false, false, false, false, false),
    YELLOW_GLAZED_TERRACOTTA(239, "minecraft:yellow_glazed_terracotta", "Yellow Glazed Terracotta", false, false, false, false, false),
    LIME_GLAZED_TERRACOTTA(240, "minecraft:lime_glazed_terracotta", "Lime Glazed Terracotta", false, false, false, false, false),
    PINK_GLAZED_TERRACOTTA(241, "minecraft:pink_glazed_terracotta", "Pink Glazed Terracotta", false, false, false, false, false),
    GRAY_GLAZED_TERRACOTTA(242, "minecraft:gray_glazed_terracotta", "Gray Glazed Terracotta", false, false, false, false, false),
    LIGHT_GRAY_GLAZED_TERRACOTTA(243, "minecraft:light_gray_glazed_terracotta", "Light Gray Glazed Terracotta", false, false, false, false, false),
    CYAN_GLAZED_TERRACOTTA(244, "minecraft:cyan_glazed_terracotta", "Cyan Glazed Terracotta", false, false, false, false, false),
    PURPLE_GLAZED_TERRACOTTA(245, "minecraft:purple_glazed_terracotta", "Purple Glazed Terracotta", false, false, false, false, false),
    BLUE_GLAZED_TERRACOTTA(246, "minecraft:blue_glazed_terracotta", "Blue Glazed Terracotta", false, false, false, false, false),
    BROWN_GLAZED_TERRACOTTA(247, "minecraft:brown_glazed_terracotta", "Brown Glazed Terracotta", false, false, false, false, false),
    GREEN_GLAZED_TERRACOTTA(248, "minecraft:green_glazed_terracotta", "Green Glazed Terracotta", false, false, false, false, false),
    RED_GLAZED_TERRACOTTA(249, "minecraft:red_glazed_terracotta", "Red Glazed Terracotta", false, false, false, false, false),
    BLACK_GLAZED_TERRACOTTA(250, "minecraft:black_glazed_terracotta", "Black Glazed Terracotta", false, false, false, false, false),
    CONCRETE(251, "minecraft:concrete", "Concrete", true, false, false, false, false),
    CONCRETE_POWDER(252, "minecraft:concrete_powder", "Concrete Powder", true, false, false, false, false),
    STRUCTURE_BLOCK(255, "minecraft:structure_block", "Structure Block", true, false, true, false, false),

    // BEGIN ITEMS

    IRON_SHOVEL(256, "minecraft:iron_shovel", "Iron Shovel", false, false, false, false, true),
    IRON_PICKAXE(257, "minecraft:iron_pickaxe", "Iron Pickaxe", false, false, false, false, true),
    IRON_AXE(258, "minecraft:iron_axe", "Iron Axe", false, false, false, false, true),
    FLINT_AND_STEEL(259, "minecraft:flint_and_steel", "Flint and Steel", false, false, false, false, true),
    APPLE(260, "minecraft:apple", "Apple", false, false, false, false, false),
    BOW(261, "minecraft:bow", "Bow", false, false, false, false, true),
    ARROW(262, "minecraft:arrow", "Arrow", false, false, false, false, false),
    COAL(263, "minecraft:coal", "Coal", false, true, false, false, false),
    DIAMOND(264, "minecraft:diamond", "Diamond", false, false, false, false, false),
    IRON_INGOT(265, "minecraft:iron_ingot", "Iron Ingot", false, false, false, false, false),
    GOLD_INGOT(266, "minecraft:gold_ingot", "Gold Ingot", false, false, false, false, false),
    IRON_SWORD(267, "minecraft:iron_sword", "Iron Sword", false, false, false, false, true),
    WOODEN_SWORD(268, "minecraft:wooden_sword", "Wooden Sword", false, false, false, false, true),
    WOODEN_SHOVEL(269, "minecraft:wooden_shovel", "Wooden Shovel", false, false, false, false, true),
    WOODEN_PICKAXE(270, "minecraft:wooden_pickaxe", "Wooden Pickaxe", false, false, false, false, true),
    WOODEN_AXE(271, "minecraft:wooden_axe", "Wooden Axe", false, false, false, false, true),
    STONE_SWORD(272, "minecraft:stone_sword", "Stone Sword", false, false, false, false, true),
    STONE_SHOVEL(273, "minecraft:stone_shovel", "Stone Shovel", false, false, false, false, true),
    STONE_PICKAXE(274, "minecraft:stone_pickaxe", "Stone Pickaxe", false, false, false, false, true),
    STONE_AXE(275, "minecraft:stone_axe", "Stone Axe", false, false, false, false, true),
    DIAMOND_SWORD(276, "minecraft:diamond_sword", "Diamond Sword", false, false, false, false, true),
    DIAMOND_SHOVEL(277, "minecraft:diamond_shovel", "Diamond Shovel", false, false, false, false, true),
    DIAMOND_PICKAXE(278, "minecraft:diamond_pickaxe", "Diamond Pickaxe", false, false, false, false, true),
    DIAMOND_AXE(279, "minecraft:diamond_axe", "Diamond Axe", false, false, false, false, true),
    STICK(280, "minecraft:stick", "Stick", false, false, false, false, false),
    BOWL(281, "minecraft:bowl", "Bowl", false, false, false, false, false),
    MUSHROOM_STEW(282, "minecraft:mushroom_stew", "Mushroom Stew", false, false, false, false, false),
    GOLDEN_SWORD(283, "minecraft:golden_sword", "Golden Sword", false, false, false, false, true),
    GOLDEN_SHOVEL(284, "minecraft:golden_shovel", "Golden Shovel", false, false, false, false, true),
    GOLDEN_PICKAXE(285, "minecraft:golden_pickaxe", "Golden Pickaxe", false, false, false, false, true),
    GOLDEN_AXE(286, "minecraft:golden_axe", "Golden Axe", false, false, false, false, true),
    STRING(287, "minecraft:string", "String", false, false, false, false, false),
    FEATHER(288, "minecraft:feather", "Feather", false, false, false, false, false),
    GUNPOWDER(289, "minecraft:gunpowder", "Gunpowder", false, false, false, false, false),
    WOODEN_HOE(290, "minecraft:wooden_hoe", "Wooden Hoe", false, false, false, false, true),
    STONE_HOE(291, "minecraft:stone_hoe", "Stone Hoe", false, false, false, false, true),
    IRON_HOE(292, "minecraft:iron_hoe", "Iron Hoe", false, false, false, false, true),
    DIAMOND_HOE(293, "minecraft:diamond_hoe", "Diamond Hoe", false, false, false, false, true),
    GOLDEN_HOE(294, "minecraft:golden_hoe", "Golden Hoe", false, false, false, false, true),
    SEEDS(295, "minecraft:wheat_seeds", "Seeds", false, false, false, false, false),
    WHEAT(296, "minecraft:wheat", "Wheat", false, false, false, false, false),
    BREAD(297, "minecraft:bread", "Bread", false, false, false, false, false),
    LEATHER_CAP(298, "minecraft:leather_helmet", "Leather Cap", false, false, false, false, true),
    LEATHER_TUNIC(299, "minecraft:leather_chestplate", "Leather Tunic", false, false, false, false, true),
    LEATHER_PANTS(300, "minecraft:leather_leggings", "Leather Pants", false, false, false, false, true),
    LEATHER_BOOTS(301, "minecraft:leather_boots", "Leather Boots", false, false, false, false, true),
    CHAIN_HELMET(302, "minecraft:chainmail_helmet", "Chain Helmet", false, false, false, false, true),
    CHAIN_CHESTPLATE(303, "minecraft:chainmail_chestplate", "Chain Chestplate", false, false, false, false, true),
    CHAIN_LEGGINGS(304, "minecraft:chainmail_leggings", "Chain Leggings", false, false, false, false, true),
    CHAIN_BOOTS(305, "minecraft:chainmail_boots", "Chain Boots", false, false, false, false, true),
    IRON_HELMET(306, "minecraft:iron_helmet", "Iron Helmet", false, false, false, false, true),
    IRON_CHESTPLATE(307, "minecraft:iron_chestplate", "Iron Chestplate", false, false, false, false, true),
    IRON_LEGGINGS(308, "minecraft:iron_leggings", "Iron Leggings", false, false, false, false, true),
    IRON_BOOTS(309, "minecraft:iron_boots", "Iron Boots", false, false, false, false, true),
    DIAMOND_HELMET(310, "minecraft:diamond_helmet", "Diamond Helmet", false, false, false, false, true),
    DIAMOND_CHESTPLATE(311, "minecraft:diamond_chestplate", "Diamond Chestplate", false, false, false, false, true),
    DIAMOND_LEGGINGS(312, "minecraft:diamond_leggings", "Diamond Leggings", false, false, false, false, true),
    DIAMOND_BOOTS(313, "minecraft:diamond_boots", "Diamond Boots", false, false, false, false, true),
    GOLDEN_HELMET(314, "minecraft:golden_helmet", "Golden Helmet", false, false, false, false, true),
    GOLDEN_CHESTPLATE(315, "minecraft:golden_chestplate", "Golden Chestplate", false, false, false, false, true),
    GOLDEN_LEGGINGS(316, "minecraft:golden_leggings", "Golden Leggings", false, false, false, false, true),
    GOLDEN_BOOTS(317, "minecraft:golden_boots", "Golden Boots", false, false, false, false, true),
    FLINT(318, "minecraft:flint", "Flint", false, false, false, false, false),
    RAW_PORKCHOP(319, "minecraft:porkchop", "Raw Porkchop", false, false, false, false, false),
    COOKED_PORKCHOP(320, "minecraft:cooked_porkchop", "Cooked Porkchop", false, false, false, false, false),
    PAINTING(321, "minecraft:painting", "Painting", false, false, false, false, false),
    GOLDEN_APPLE(322, "minecraft:golden_apple", "Golden Apple", false, true, false, false, false),
    SIGN_ITEM(323, "minecraft:sign", "Sign", false, false, false, false, false),
    OAK_DOOR_ITEM(324, "minecraft:wooden_door", "Oak Door", false, false, false, false, false),
    BUCKET(325, "minecraft:bucket", "Bucket", false, false, false, false, false),
    WATER_BUCKET(326, "minecraft:water_bucket", "Water Bucket", false, false, false, false, false),
    LAVA_BUCKET(327, "minecraft:lava_bucket", "Lava Bucket", false, false, false, false, false),
    MINECART(328, "minecraft:minecart", "Minecart", false, false, false, false, false),
    SADDLE(329, "minecraft:saddle", "Saddle", false, false, false, false, false),
    IRON_DOOR_ITEM(330, "minecraft:iron_door", "Iron Door", false, false, false, false, false),
    REDSTONE(331, "minecraft:redstone", "Redstone", false, false, false, false, false),
    SNOWBALL(332, "minecraft:snowball", "Snowball", false, false, false, false, false),
    BOAT(333, "minecraft:boat", "Boat", false, false, false, false, false),
    LEATHER(334, "minecraft:leather", "Leather", false, false, false, false, false),
    MILK(335, "minecraft:milk_bucket", "Milk", false, false, false, false, false),
    BRICK(336, "minecraft:brick", "Brick", false, false, false, false, false),
    CLAY_BALL(337, "minecraft:clay_ball", "Clay", false, false, false, false, false),
    SUGAR_CANE_ITEM(338, "minecraft:reeds", "Sugar Cane", false, false, false, false, false),
    PAPER(339, "minecraft:paper", "Paper", false, false, false, false, false),
    BOOK(340, "minecraft:book", "Book", false, false, false, false, false),
    SLIMEBALL(341, "minecraft:slime_ball", "Slimeball", false, false, false, false, false),
    MINECART_WITH_CHEST(342, "minecraft:chest_minecart", "Minecart with Chest", false, false, false, false, false),
    MINECART_WITH_FURNACE(343, "minecraft:furnace_minecart", "Minecart with Furnace", false, false, false, false, false),
    EGG(344, "minecraft:egg", "Egg", false, false, false, false, false),
    COMPASS(345, "minecraft:compass", "Compass", false, false, false, false, false),
    FISHING_ROD(346, "minecraft:fishing_rod", "Fishing Rod", false, false, false, false, true),
    CLOCK(347, "minecraft:clock", "Clock", false, false, false, false, false),
    GLOWSTONE_DUST(348, "minecraft:glowstone_dust", "Glowstone Dust", false, false, false, false, false),
    RAW_FISH(349, "minecraft:fish", "Raw Fish", false, true, false, false, false),
    COOKED_FISH(350, "minecraft:cooked_fish", "Cooked Fish", false, true, false, false, false),
    DYE(351, "minecraft:dye", "Dye", false, true, false, false, false),
    BONE(352, "minecraft:bone", "Bone", false, false, false, false, false),
    SUGAR(353, "minecraft:sugar", "Sugar", false, false, false, false, false),
    CAKE_ITEM(354, "minecraft:cake", "Cake", false, false, false, false, false),
    BED_ITEM(355, "minecraft:bed", "Bed", false, false, false, false, false),
    REDSTONE_REPEATER_ITEM(356, "minecraft:repeater", "Redstone Repeater", false, false, false, false, false),
    COOKIE(357, "minecraft:cookie", "Cookie", false, false, false, false, false),
    MAP(358, "minecraft:filled_map", "Map", false, true, false, false, false),
    SHEARS(359, "minecraft:shears", "Shears", false, false, false, false, true),
    MELON_ITEM(360, "minecraft:melon", "Melon", false, false, false, false, false),
    PUMPKIN_SEEDS(361, "minecraft:pumpkin_seeds", "Pumpkin Seeds", false, false, false, false, false),
    MELON_SEEDS(362, "minecraft:melon_seeds", "Melon Seeds", false, false, false, false, false),
    RAW_BEEF(363, "minecraft:beef", "Raw Beef", false, false, false, false, false),
    STEAK(364, "minecraft:cooked_beef", "Steak", false, false, false, false, false),
    RAW_CHICKEN(365, "minecraft:chicken", "Raw Chicken", false, false, false, false, false),
    COOKED_CHICKEN(366, "minecraft:cooked_chicken", "Cooked Chicken", false, false, false, false, false),
    ROTTEN_FLESH(367, "minecraft:rotten_flesh", "Rotten Flesh", false, false, false, false, false),
    ENDER_PEARL(368, "minecraft:ender_pearl", "Ender Pearl", false, false, false, false, false),
    BLAZE_ROD(369, "minecraft:blaze_rod", "Blaze Rod", false, false, false, false, false),
    GHAST_TEAR(370, "minecraft:ghast_tear", "Ghast Tear", false, false, false, false, false),
    GOLD_NUGGET(371, "minecraft:gold_nugget", "Gold Nugget", false, false, false, false, false),
    NETHER_WART(372, "minecraft:nether_wart", "Nether Wart", false, false, false, false, false),
    POTION(373, "minecraft:potion", "Potion", false, true, false, false, false),
    GLASS_BOTTLE(374, "minecraft:glass_bottle", "Glass Bottle", false, false, false, false, false),
    SPIDER_EYE(375, "minecraft:spider_eye", "Spider Eye", false, false, false, false, false),
    FERMENTED_SPIDER_EYE(376, "minecraft:fermented_spider_eye", "Fermented Spider Eye", false, false, false, false, false),
    BLAZE_POWDER(377, "minecraft:blaze_powder", "Blaze Powder", false, false, false, false, false),
    MAGMA_CREAM(378, "minecraft:magma_cream", "Magma Cream", false, false, false, false, false),
    BREWING_STAND_ITEM(379, "minecraft:brewing_stand", "Brewing Stand", false, false, false, false, false),
    CAULDRON_ITEM(380, "minecraft:cauldron", "Cauldron", false, false, false, false, false),
    EYE_OF_ENDER(381, "minecraft:ender_eye", "Eye of Ender", false, false, false, false, false),
    GLISTERING_MELON(382, "minecraft:speckled_melon", "Glistering Melon", false, false, false, false, false),
    SPAWN_EGG(383, "minecraft:spawn_egg", "Spawn Egg", false, true, false, false, false),
    BOTTLE_O__ENCHANTING(384, "minecraft:experience_bottle", "Bottle o' Enchanting", false, false, false, false, false),
    FIRE_CHARGE(385, "minecraft:fire_charge", "Fire Charge", false, false, false, false, false),
    BOOK_AND_QUILL(386, "minecraft:writable_book", "Book and Quill", false, false, false, false, false),
    WRITTEN_BOOK(387, "minecraft:written_book", "Written Book", false, false, false, false, false),
    EMERALD(388, "minecraft:emerald", "Emerald", false, false, false, false, false),
    ITEM_FRAME(389, "minecraft:item_frame", "Item Frame", false, false, false, false, false),
    FLOWER_POT_ITEM(390, "minecraft:flower_pot", "Flower Pot", false, false, false, false, false),
    CARROT(391, "minecraft:carrot", "Carrot", false, false, false, false, false),
    POTATO(392, "minecraft:potato", "Potato", false, false, false, false, false),
    BAKED_POTATO(393, "minecraft:baked_potato", "Baked Potato", false, false, false, false, false),
    POISONOUS_POTATO(394, "minecraft:poisonous_potato", "Poisonous Potato", false, false, false, false, false),
    EMPTY_MAP(395, "minecraft:map", "Empty Map", false, false, false, false, false),
    GOLDEN_CARROT(396, "minecraft:golden_carrot", "Golden Carrot", false, false, false, false, false),
    MOB_HEAD_ITEM(397, "minecraft:skull", "Mob head", false, true, false, false, false),
    CARROT_ON_A_STICK(398, "minecraft:carrot_on_a_stick", "Carrot on a Stick", false, false, false, false, true),
    NETHER_STAR(399, "minecraft:nether_star", "Nether Star", false, false, false, false, false),
    PUMPKIN_PIE(400, "minecraft:pumpkin_pie", "Pumpkin Pie", false, false, false, false, false),
    FIREWORK_ROCKET(401, "minecraft:fireworks", "Firework Rocket", false, false, false, false, false),
    FIREWORK_STAR(402, "minecraft:firework_charge", "Firework Star", false, false, false, false, false),
    ENCHANTED_BOOK(403, "minecraft:enchanted_book", "Enchanted Book", false, false, false, false, false),
    REDSTONE_COMPARATOR_ITEM(404, "minecraft:comparator", "Redstone Comparator", false, false, false, false, false),
    NETHER_BRICK_ITEM(405, "minecraft:netherbrick", "Nether Brick", false, false, false, false, false),
    NETHER_QUARTZ(406, "minecraft:quartz", "Nether Quartz", false, false, false, false, false),
    MINECART_WITH_TNT(407, "minecraft:tnt_minecart", "Minecart with TNT", false, false, false, false, false),
    MINECART_WITH_HOPPER(408, "minecraft:hopper_minecart", "Minecart with Hopper", false, false, false, false, false),
    PRISMARINE_SHARD(409, "minecraft:prismarine_shard", "Prismarine Shard", false, false, false, false, false),
    PRISMARINE_CRYSTALS(410, "minecraft:prismarine_crystals", "Prismarine Crystals", false, false, false, false, false),
    RAW_RABBIT(411, "minecraft:rabbit", "Raw Rabbit", false, false, false, false, false),
    COOKED_RABBIT(412, "minecraft:cooked_rabbit", "Cooked Rabbit", false, false, false, false, false),
    RABBIT_STEW(413, "minecraft:rabbit_stew", "Rabbit Stew", false, false, false, false, false),
    RABBIT_FOOT(414, "minecraft:rabbit_foot", "Rabbit's Foot", false, false, false, false, false),
    RABBIT_HIDE(415, "minecraft:rabbit_hide", "Rabbit Hide", false, false, false, false, false),
    ARMOR_STAND(416, "minecraft:armor_stand", "Armor Stand", false, false, false, false, false),
    IRON_HORSE_ARMOR(417, "minecraft:iron_horse_armor", "Iron Horse Armor", false, false, false, false, false),
    GOLDEN_HORSE_ARMOR(418, "minecraft:golden_horse_armor", "Golden Horse Armor", false, false, false, false, false),
    DIAMOND_HORSE_ARMOR(419, "minecraft:diamond_horse_armor", "Diamond Horse Armor", false, false, false, false, false),
    LEAD(420, "minecraft:lead", "Lead", false, false, false, false, false),
    NAME_TAG(421, "minecraft:name_tag", "Name Tag", false, false, false, false, false),
    MINECART_WITH_COMMAND_BLOCK(422, "minecraft:command_block_minecart", "Minecart with Command Block", false, false, false, false, false),
    RAW_MUTTON(423, "minecraft:mutton", "Raw Mutton", false, false, false, false, false),
    COOKED_MUTTON(424, "minecraft:cooked_mutton", "Cooked Mutton", false, false, false, false, false),
    BANNER_ITEM(425, "minecraft:banner", "Banner", false, false, false, false, false),
    END_CRYSTAL(426, "minecraft:end_crystal", "End Crystal", false, false, false, false, false),
    SPRUCE_DOOR_ITEM(427, "minecraft:spruce_door", "Spruce Door", false, false, false, false, false),
    BIRCH_DOOR_ITEM(428, "minecraft:birch_door", "Birch Door", false, false, false, false, false),
    JUNGLE_DOOR_ITEM(429, "minecraft:jungle_door", "Jungle Door", false, false, false, false, false),
    ACACIA_DOOR_ITEM(430, "minecraft:acacia_door", "Acacia Door", false, false, false, false, false),
    DARK_OAK_DOOR_ITEM(431, "minecraft:dark_oak_door", "Dark Oak Door", false, false, false, false, false),
    CHORUS_FRUIT(432, "minecraft:chorus_fruit", "Chorus Fruit", false, false, false, false, false),
    POPPED_CHORUS_FRUIT(433, "minecraft:chorus_fruit_popped", "Popped Chorus Fruit", false, false, false, false, false),
    BEETROOT(434, "minecraft:beetroot", "Beetroot", false, false, false, false, false),
    BEETROOT_SEEDS(435, "minecraft:beetroot_seeds", "Beetroot Seeds", false, false, false, false, false),
    BEETROOT_SOUP(436, "minecraft:beetroot_soup", "Beetroot Soup", false, false, false, false, false),
    DRAGONS_BREATH(437, "minecraft:dragon_breath", "Dragon's Breath", false, false, false, false, false),
    SPLASH_POTION(438, "minecraft:splash_potion", "Splash Potion", false, false, false, false, false),
    SPECTRAL_ARROW(439, "minecraft:spectral_arrow", "Spectral Arrow", false, false, false, false, false),
    TIPPED_ARROW(440, "minecraft:tipped_arrow", "Tipped Arrow", false, false, false, false, false),
    LINGERING_POTION(441, "minecraft:lingering_potion", "Lingering Potion", false, false, false, false, false),
    SHIELD(442, "minecraft:shield", "Shield", false, false, false, false, false),
    ELYTRA(443, "minecraft:elytra", "Elytra", false, false, false, false, false),
    SPRUCE_BOAT(444, "minecraft:spruce_boat", "Spruce Boat", false, false, false, false, false),
    BIRCH_BOAT(445, "minecraft:birch_boat", "Birch Boat", false, false, false, false, false),
    JUNGLE_BOAT(446, "minecraft:jungle_boat", "Jungle Boat", false, false, false, false, false),
    ACACIA_BOAT(447, "minecraft:acacia_boat", "Acacia Boat", false, false, false, false, false),
    DARK_OAK_BOAT(448, "minecraft:dark_oak_boat", "Dark Oak Boat", false, false, false, false, false),
    TOTEM_OF_UNDYING(449, "minecraft:totem_of_undying", "Totem of Undying", false, false, false, false, false),
    SHULKER_SHELL(450, "minecraft:shulker_shell", "Shulker Shell", false, false, false, false, false),
    IRON_NUGGET(452, "minecraft:iron_nugget", "Iron Nugget", false, false, false, false, false),
    DISC_13(2256, "minecraft:record_13", "13 Disc", false, false, false, false, false),
    CAT_DISC(2257, "minecraft:record_cat", "Cat Disc", false, false, false, false, false),
    BLOCKS_DISC(2258, "minecraft:record_blocks", "Blocks Disc", false, false, false, false, false),
    CHIRP_DISC(2259, "minecraft:record_chirp", "Chirp Disc", false, false, false, false, false),
    FAR_DISC(2260, "minecraft:record_far", "Far Disc", false, false, false, false, false),
    MALL_DISC(2261, "minecraft:record_mall", "Mall Disc", false, false, false, false, false),
    MELLOHI_DISC(2262, "minecraft:record_mellohi", "Mellohi Disc", false, false, false, false, false),
    STAL_DISC(2263, "minecraft:record_stal", "Stal Disc", false, false, false, false, false),
    STRAD_DISC(2264, "minecraft:record_strad", "Strad Disc", false, false, false, false, false),
    WARD_DISC(2265, "minecraft:record_ward", "Ward Disc", false, false, false, false, false),
    DISC_11(2266, "minecraft:record_11", "11 Disc", false, false, false, false, false),
    WAIT_DISC(2267, "minecraft:record_wait", "Wait Disc", false, false, false, false, false);

    /**
     * The Substance&#x27;s numeric ID
     */
    private final int id;

    /**
     * The Substance&#x27;s string ID
     */
    private final String stringId;

    /**
     * The Substance&#x27;s display name
     */
    private final String displayName;

    /**
     * Whether this Substance needs data.
     */
    private final boolean needsData;

    /**
     * Whether this Substance needs damage.
     */
    private final boolean needsDamage;

    /**
     * Whether this Substance needs a block entity.
     */
    private final boolean needsBlockEntity;

    /**
     * Whether this Substance has a different ID in item form to when in block form.
     */
    private final boolean hasSeparateItemID;

    /**
     * Whether this Substance has durability.
     */
    private final boolean hasDurability;

    /**
     * The constructor for all Substances.
     */
    private Substance(int id, String stringId, String displayName, boolean needsData, boolean needsDamage, boolean needsBlockEntity, boolean hasSeparateItemID, boolean hasDurability) {
        this.id = id;
        this.stringId = stringId;
        this.displayName = displayName;
        this.needsData = needsData;
        this.needsDamage = needsDamage;
        this.needsBlockEntity = needsBlockEntity;
        this.hasSeparateItemID = hasSeparateItemID;
        this.hasDurability = hasDurability;
    }

    /**
     * Gets the Substance&#x27;s numeric ID.
     *
     * @return The Substance&#x27;s numeric ID
     */
    public int getId() {
        return this.id;
    }

    /**
     * Gets the Substance&#x27;s string ID.
     *
     * @return The Substance&#x27;s string ID
     */
    public String getStringId() {
        return this.stringId;
    }

    /**
     * Gets the Substance&#x27;s display name
     *
     * @return The Substance&#x27;s display name
     */
    public String getDisplayName() {
        return this.displayName;
    }

    /**
     * Gets whether additional data from the saved game&#x27;s Data array is required to fully define the Substance.
     *
     * @return Whether this Substance needs data.
     */
    public boolean needsData() {
        return this.needsData;
    }

    /**
     * Gets whether additional data in the Substance&#x27;s Damage field is required to fully define the inventory item.
     *
     * @return Whether this Substance needs damage.
     */
    public boolean needsDamage() {
        return this.needsDamage;
    }

    /**
     * Gets whether a block entity is required to store additional data about the Substance.
     *
     * @return Whether this Substance needs a block entity.
     */
    public boolean needsBlockEntity() {
        return this.needsBlockEntity;
    }

    /**
     * Gets whether this Substance has a separate ID when it an inventory item.
     *
     * @return Whether this Substance has a different ID in item form to when in block form.
     */
    public boolean hasSeparateItemID() {
        return this.hasSeparateItemID;
    }

    /**
     * Gets whether this Substance uses the Damage field to define its durability.
     *
     * @return Whether this Substance has durability.
     */
    public boolean hasDurability() {
        return this.hasDurability;
    }

    /**
     * Gets if this Substance is a block.
     *
     * @return true iff it is a block
     */
    public boolean isBlock() {
        return this.id <= 255; // generated
    }

    /**
     * Gets if this Substance is an item.
     *
     * @return true iff it is an item
     */
    public boolean isItem() {
        return !this.isBlock();
    }

    @Override
    public String toString() {
        return this.stringId;
    }

    /**
     * Mappings of ID values to their respective substances,
     * substances can contain 400+ entries and that is not
     * worth using O(n) iteration.
     */
    private static final Int2ReferenceOpenHashMap<Substance> SUBSTANCE_BY_NUMERIC_MAP = new Int2ReferenceOpenHashMap<>();
    private static final Map<String, Substance> SUBSTANCE_BY_STRING_MAP = new HashMap<>();
    private static final Map<String, Substance> SUBSTANCE_BY_NAME_MAP = new HashMap<>();

    static {
        for (Substance s : values()) {
            SUBSTANCE_BY_NUMERIC_MAP.put(s.id, s);
            SUBSTANCE_BY_STRING_MAP.put(s.stringId, s);
            SUBSTANCE_BY_NAME_MAP.put(s.displayName, s);
        }
        SUBSTANCE_BY_NUMERIC_MAP.trim();
    }

    /**
     * Obtains the substance that is represented by the
     * given ID value.
     *
     * @param id the ID value of the substance to find
     * @return the substance
     */
    public static Substance fromNumericId(int id) {
        Substance substance = SUBSTANCE_BY_NUMERIC_MAP.get(id);
        if (substance == null) {
            throw new IllegalArgumentException("Invalid Substance ID (" + id + ")");
        }
        return substance;
    }

    /**
     * Obtains the substance that is represented by the
     * given string ID.
     *
     * @param id the string ID value of the substance to find
     * @return the substance
     */
    public static Substance fromStringId(String id) {
        Substance substance = SUBSTANCE_BY_STRING_MAP.get(id);
        if (substance == null) {
            throw new IllegalArgumentException("Invalid Substance ID (" + id + ")");
        }
        return substance;
    }

    /**
     * Obtains the substance with the given name.
     *
     * @param name the name of the substance to find
     * @return the substance
     */
    public static Substance fromName(String name) {
        Substance substance = SUBSTANCE_BY_NAME_MAP.get(name);
        if (substance == null) {
            throw new IllegalArgumentException("Invalid Substance name (" + name + ")");
        }
        return substance;
    }

}
